### ISSUE TITLE
libav tools not available in docker

### ISSUE THREAD

**Issue by flip-arunkp** [Rayhane-mamah/Tacotron-2#438]
Hi, 

I am trying to run the docker build and it fails saying that libav tools package is not available. How can i fix this?

Thanks

**Comment by flip-arunkp** [comment]
Also the docker tensorflow 2.0 is being pulled and this doesnt work with 2.0. What is the version of tensorflow supported?

**Comment by JasonWei512** [comment]
Tensorflow 1.10

Just install libav tools manually:
```
wget http://launchpadlibrarian.net/339874908/libav-tools_3.3.4-2_all.deb
dpkg -i libav-tools_3.3.4-2_all.deb
```

**Comment by flip-arunkp** [comment]
Tensorflow 1.10 gives error: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

**Comment by cschaefer26** [comment]
Probably misfit of the Keras version, try

`pip install keras==2.2.4`

**Comment by flip-arunkp** [comment]
the keras version fix helps. Thanks. I will close the issue
