### ISSUE TITLE
unexpected keyword argument 'previous_alignments'

### ISSUE THREAD

**Issue by zhf459** [Rayhane-mamah/Tacotron-2#12]
```
Traceback (most recent call last):
  File "/home/zeng/work/pycharm/Tacotron-2/train.py", line 32, in <module>
    main()
  File "/home/zeng/work/pycharm/Tacotron-2/train.py", line 26, in main
    tacotron_train(args)
  File "/home/zeng/work/pycharm/Tacotron-2/tacotron/train.py", line 183, in tacotron_train
    train(log_dir, args)
  File "/home/zeng/work/pycharm/Tacotron-2/tacotron/train.py", line 73, in train
    model.initialize(feeder.inputs, feeder.input_lengths, feeder.mel_targets, feeder.token_targets)
  File "/home/zeng/work/pycharm/Tacotron-2/tacotron/models/tacotron.py", line 106, in initialize
    maximum_iterations=max_iters)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 234, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/zeng/work/pycharm/Tacotron-2/tacotron/models/custom_decoder.py", line 123, in step
    (cell_outputs, stop_token), cell_state = self._cell(inputs, state)
  File "/home/zeng/work/pycharm/Tacotron-2/tacotron/models/Architecture_wrappers.py", line 194, in __call__
    attention_layer=None)
  File "/home/zeng/tf_gpu_py3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 973, in _compute_attention
    cell_output, previous_alignments=previous_alignments)
TypeError: __call__() got an unexpected keyword argument 'previous_alignments'
```
Hi,Rayhane-mamah, greate job! I try to train the model,but get this error.it seems that `previous_alignments` is not a parameter in `LocationSensitiveAttention` ? anything wrong?

**Comment by Rayhane-mamah** [comment]
Hello,

You need tensorflow 1.6 indeed.

@butterl I didn't want to add it there to not affect pre installed tensorflow gpu. I will however try to add working version for tf 1.4.

**Comment by zhf459** [comment]
@Rayhane-mamah ,I hope it works for tf 1.4 too.

**Comment by Rayhane-mamah** [comment]
It doesn't for now, I will try adding this dependency in the next 24 hours if you don't want to upgrade.

Sorry for the inconvenience.

**Comment by Rayhane-mamah** [comment]
Hello again,

Tensorflow 1.6 is not longer a must, I added the possibility to use the project with tensorflow 1.4 in this commit (0330bd0161e4530acbb7bc2db00a1db95b2dc107).

For that purpose I added the [attention_old.py](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/tacotron/models/attention_old.py) file. It might have been possible to simply change the function call in the same existing **attention.py** file, but I wanted to avoid any conflicts so I made a copy of the attention file and adapted the call function to work with Tensorflow 1.4 API.

If there still are some issues, please report them.

**Comment by zhf459** [comment]
@Rayhane-mamah that's great, thank you!

**Comment by ArashHosseini** [comment]
@Rayhane-mamah can you tell me more about [this issue](https://github.com/keithito/tacotron/issues/172) please. thank you

**Comment by ArloZ** [comment]
Hello @Rayhane-mamah 
when i try to train the model, it raise an error with Tensorflow 1.4 .  
is there a way to fix it ? thank you ~
```
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    main()
  File "train.py", line 75, in main
    train(args, log_dir, hparams)
  File "train.py", line 27, in train
    checkpoint = tacotron_train(args, log_dir, hparams)
  File "/root/synthetic/tacotron-2/tacotron/train.py", line 329, in tacotron_train
    train(log_dir, args, hparams)
  File "/root/synthetic/tacotron-2/tacotron/train.py", line 139, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "/root/synthetic/tacotron-2/tacotron/train.py", line 75, in model_train_mode
    is_training=True)
  File "/root/synthetic/tacotron-2/tacotron/models/tacotron.py", line 69, in initialize
    zoneout=hp.tacotron_zoneout_rate, scope='encoder_LSTM'))
  File "/root/synthetic/tacotron-2/tacotron/models/modules.py", line 139, in __init__
    name='encoder_fw_LSTM')
  File "/root/synthetic/tacotron-2/tacotron/models/modules.py", line 39, in __init__
    self._cell = tf.nn.rnn_cell.LSTMCell(num_units, state_is_tuple=state_is_tuple, name=name)
TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by ArashHosseini** [comment]
@Rayhane-mamah, Thank you for your answer. I tried your "new" attention.py file, again I hit the "TypeError: __call __ () got an unexpected keyword argument 'previous_alignments'
" error.
But before that I would like to try your repo. i used the preprocess step and on training:

```
python3.5 train.py
Using TensorFlow backend.

#############################################################

Tacotron Train

###########################################################

Checkpoint path: logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt
Loading training data from: training_data/train.txt
Using model: Tacotron-2
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cin_channels: 80
  cleaners: english_cleaners
  clip_mels_length: True
  cross_entropy_pos_weight: 20
  cumulative_weights: True
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fft_size: 1024
  fmax: 7600
  fmin: 125
  frame_shift_ms: None
  freq_axis_kernel_size: 3
  gate_channels: 512
  gin_channels: -1
  griffin_lim_iters: 60
  hop_size: 256
  input_type: raw
  kernel_size: 3
  layers: 24
  log_scale_min: -32.23619130191664
  mask_decoder: True
  mask_encoder: True
  max_abs_value: 4.0
  max_iters: 2500
  max_mel_frames: 900
  max_time_sec: None
  max_time_steps: 13000
  min_level_db: -100
  num_freq: 513
  num_gpus: 1
  num_mels: 80
  out_channels: 30
  outputs_per_step: 1
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.2
  predict_linear: False
  prenet_layers: [256, 256]
  quantize_channels: 65536
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.999
  residual_channels: 512
  sample_rate: 22050
  signal_normalization: True
  silence_threshold: 2
  skip_out_channels: 256
  smoothing: False
  stacks: 4
  stop_at_any: True
  symmetric_mels: True
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 32
  tacotron_data_random_state: 1234
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.2
  tacotron_decay_steps: 40000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_initial_learning_rate: 0.001
  tacotron_random_seed: 5339
  tacotron_reg_weight: 1e-06
  tacotron_scale_regularization: False
  tacotron_start_decay: 50000
  tacotron_swap_with_cpu: False
  tacotron_teacher_forcing_decay_alpha: 0.0
  tacotron_teacher_forcing_decay_steps: 220000
  tacotron_teacher_forcing_final_ratio: 0.0
  tacotron_teacher_forcing_init_ratio: 1.0
  tacotron_teacher_forcing_mode: constant
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_teacher_forcing_start_decay: 10000
  tacotron_test_batches: 48
  tacotron_test_size: None
  tacotron_zoneout_rate: 0.1
  train_with_GTA: False
  trim_silence: True
  upsample_conditional_features: True
  upsample_scales: [16, 16]
  use_all_gpus: False
  use_bias: True
  use_lws: True
  wavenet_adam_beta1: 0.9
  wavenet_adam_beta2: 0.999
  wavenet_adam_epsilon: 1e-06
  wavenet_batch_size: 4
  wavenet_data_random_state: 1234
  wavenet_dropout: 0.05
  wavenet_ema_decay: 0.9999
  wavenet_learning_rate: 0.0001
  wavenet_random_seed: 5339
  wavenet_swap_with_cpu: False
  wavenet_test_batches: None
  wavenet_test_size: 0.0441
Loaded metadata for 13100 examples (24.06 hours)
Segmentation fault (core dumped)
```

**Comment by Rayhane-mamah** [comment]
Our latest version are independent from tensorflow's attention wrappers so this issue should be fixed.
